DROP TABLE ARTICULOS;
DROP TABLE MARCAS;

CREATE TABLE MARCAS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    CODIGO CHAR(5),
    TIPO_DE_MARCA VARCHAR(20) NOT NULL, -- Periféricos, CPU, etc
    NOMBRE_MARCA VARCHAR(30),
    CONSTRAINT ID_MARCAS_PK PRIMARY KEY (ID)
);

CREATE TABLE ARTICULOS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, -- Id autonumérico
    NOMBRE VARCHAR(20) NOT NULL, -- Nombre completo del producto
    STOCK SMALLINT NOT NULL,
    DESCRIPCION VARCHAR(255),
    STOCK_MIN CHAR(10),
    STOCK_MAX CHAR(70),
    MARCA INT,
    PERIFERICO BOOLEAN, -- Para saber si el artículo es un periférico o no
    PRECIO DECIMAL(10,2),
    SEGUNDA_MANO BOOLEAN,
    FOTO_DEL_ARTICULO VARCHAR(30),
    CONSTRAINT ID_ARTICULOS_PK PRIMARY KEY (ID),
    CONSTRAINT MAR_ARTICULOS_FK FOREIGN KEY (MARCA) REFERENCES MARCAS (ID)
);
-- nombre, descripcion y nombre_marca(marcas)